version: '3'

volumes:
  workflow-buddy:
    name: workflow-buddy

services:
  workflow-buddy:
    build: '.'
    ports:
      - '4747:4747'
    volumes:
      - workflow-buddy:/usr/app/data/
    environment:
    # Docker Compose loads from .env file automatically
      ENV: PROD
      LOG_LEVEL: DEBUG # shouldn't show on Fly deploys, but useful locally
      WB_DATA_DIR: /usr/app/data/
      # SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
