name: "ðŸ› Bug Report"
description: Create a report to help us improve Workflow Buddy
body:
  - type: markdown
    attributes:
     value: |
       Thanks for taking the time to fill out this bug report!

       Please note that this tracker is only for bugs. Do not use the issue tracker for help, customer support or feature requests.

       **Thanks!**
  - type: checkboxes
    attributes:
      label: Past Issues Searched
      options:
        - label: >-
            I have searched open and closed issues to make sure that the bug has
            not yet been reported
          required: true
  - type: checkboxes
    attributes:
      label: Issue is a Bug Report
      options:
        - label: >-
            This is a bug report and not a feature request
          required: true
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: bug-expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what you expected
    validations:
      required: true
  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: 'If applicable, add screenshots to help explain your problem'
      placeholder: Insert screenshots here
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - **OS**: MacOS
        - **Slack Client**: Desktop/Web/Mobile
      value: |
        - OS:
        - Slack Client:
      render: markdown
